### ISSUE TITLE
URI Decision Points

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#42]
**ISSUE**
In order to answer some of the infrastructure questions Rick and team have asked, we need to make some provisional* decisions about what kinds of URLs and URIs we want for the system.

*The goal of this round of conversations is understand if there are any hard deadlines or decisions that we can't easily modify later on.  Then based on any constraints that surface in those discussions, what provisional (or permanent) names and endpoints do we need to set up to get us moving?

**ACCEPTANCE**
- [x] Key team members have reviewed this deck: https://docs.google.com/presentation/d/1p58-Prs_ZQAqAj73uYvt8YIRhl02edc-ivNUkj8RtY4/edit#slide=id.g71e953a383_0_74
    - [x] Rick
    - [ ] Bob
    - [ ] Rebecca
    - [x] Mike
    - [ ] Julie
    - [x] McClain
- [ ] We have documented any decisions we can make now
- [ ] We have written tickets for any further work that needs to be done

**Comment by mark-dce** [comment]
@geekscruff @bobrice @ rebeccahirsch @ra359 I've tagged each of you to give this a look over.  Feel free to add any comments or thoughts directly on the deck or in the comments here. 

I'm assuming Rebecca might have thoughts about the Usability questions and Rick & Bob might have more input on the Technical questions, so feel free to ignore stuff that doesn't seem relevant from your perspective - but also feel free to kibbitz outside your realm of expertise ;)

**Comment by ra359** [comment]
i added some comments fyi
